# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email "james@firefly-iii.org"
    git config --global user.name "James Cole"
  displayName: 'Do Git config'

- script: |
    cd BaseImage
    php build/generate-docker-files.php
  displayName: 'Run script to generate docker files.'

- script: |
    cd BaseImage
    git status
    git add Dockerfile
    git commit -m "Auto-update Dockerfile."
    git push
  displayName: 'Commit changed to Git.'

- checkout: self
  clean: true