# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

variables:
- name: buildPhpVersion
  value: 7.4 

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email "james@firefly-iii.org"
    git config --global user.name "James Cole"
  displayName: 'Do Git config'

- script: |
    cd BaseImage
    php build/generate-docker-files.php . ${{ variables.buildPhpVersion }}
  displayName: 'Run script to generate docker files.'

- script: |
    cd BaseImage
    git checkout main
    git status
    git add Dockerfile Dockerfile.original apache2-foreground docker-php-entrypoint docker-php-ext-configure docker-php-ext-enable docker-php-ext-install docker-php-source
    git commit -m "Auto-update build files."
    git push
  displayName: 'Commit changed to Git.'



- checkout: self
  clean: true